<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="C0TDJG3" failures="1" tests="2" name="TestRunner.TestRunner" time="44.140" errors="0" timestamp="2023-04-20T17:36:53 IST" skipped="0">
  <testcase classname="TestRunner.TestRunner" name="runScenario" time="17.364">
    <failure message="Exception in create Issue of Update Issue" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Exception in create Issue of Update Issue
at org.testng.Assert.fail(Assert.java:110)
at StepDefinitions.DeleteIssue.user_creates_an_issue_for_delete_with_values(DeleteIssue.java:58)
at âœ½.User creates an issue for delete with values "[All Projects] Selenium" "random" "trial" "low" "not able to login" "description"(file:///C:/Users/sahildjindal/Documents/SDET%20Learning/GroupProject1/groupone/Features/C)deleteIssue.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="TestRunner.TestRunner" name="runScenario" time="26.776"/>
  <system-out/>
</testsuite> <!-- TestRunner.TestRunner -->
